apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: logger
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: logger
            env:
            - name: LOGS_PER_SECOND
              value: "5000"
