apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: openshift-logging
labels:
  - pairs:
      app.kubernetes.io/name: logging-benchmarking
      app.kubernetes.io/component: loader
    includeSelectors: true 
    includeTemplates: true 
resources:
- log_generator_deployment.yaml
- servicemonitor.yaml
- service.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: logger
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: logger
            image: quay.io/jcantril/cluster-logging-load-client:with_metrics
