apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/pipelines/0/outputRefs/0
      value: receiver-otlp
  target:
    kind: ClusterLogForwarder
- patch: |-
    apiVersion: "observability.openshift.io/v1"
    kind: ClusterLogForwarder
    metadata:
      name: collector
      namespace: openshift-logging
      annotations:
        observability.openshift.io/tech-preview-otlp-output: enabled
    spec:
      outputs:
      - name: receiver-otlp
        type: otlp
        otlp:
          url: http://otlp-receiver.openshift-logging.svc:4318/v1/logs
