apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: logging-benchmarking
    app.kubernetes.io/component: receiver
    app.kubernetes.io/instance: otlp
  name: otlp-receiver
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/name: logging-benchmarking
    app.kubernetes.io/component: receiver
    app.kubernetes.io/instance: otlp