apiVersion: "observability.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: collector
  namespace: openshift-logging 
spec:
  serviceAccount:
    name: logcollector
  outputs:
  - name: receiver
    type: http
    http:
      url: http://http-receiver.openshift-logging.svc:8090