apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-logging
generatorOptions:
  disableNameSuffixHash: true
resources:
- serviceaccount.yaml
- clusterrolebinding.yaml
- clusterlogforwarder.yaml