apiVersion: v1
kind: ServiceAccount
metadata:
  name: logcollector
---
apiVersion: v1
kind: Secret
metadata:
  name: logcollector-sa-token
  annotations:
    kubernetes.io/service-account.name: logcollector
type: kubernetes.io/service-account-token
