apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-logging
generatorOptions:
  disableNameSuffixHash: true
resources:
- ../../base
patches:
- path: patch_in_audit_generator.yaml