{
 "title": "Collector Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Generators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_labels{label_app_kubernetes_io_component=\"loader\",label_app_kubernetes_io_name=\"logging-benchmarking\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate + on(namespace)group_left(pod)kube_pod_labels{label_app_kubernetes_io_component=\"collector\",label_app_kubernetes_io_managed_by=\"cluster-logging-operator\"}*0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_namespace_pod_container:container_memory_rss + on(namespace)group_left(pod)kube_pod_labels{label_app_kubernetes_io_component=\"collector\",label_app_kubernetes_io_managed_by=\"cluster-logging-operator\"}*0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Throughput Rate (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(component_type)(irate(vector_component_received_event_bytes_total{component_kind=\"source\", app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\",component_type!=\"internal_metrics\"}[5m]))",
     "legendFormat": "Collected {{component_type}}"
    },
    {
     "expr": "sum by(component_type)(irate(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\",app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\"}[5m]))",
     "legendFormat": "Sent {{component_type}}"
    }
   ]
  },
  {
   "title": "Total Throughput Rate (events)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component_type)(irate(vector_component_received_events_total{component_kind=\"source\", app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\", component_type!=\"internal_metrics\"}[5m]))",
     "legendFormat": "Collected {{component_type}}"
    },
    {
     "expr": "sum by (component_type)(irate(vector_component_sent_events_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\",app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\"}[5m]))",
     "legendFormat": "Sent {{component_type}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container)(kube_pod_container_status_restarts_total{namespace=\"openshift-logging\",container=\"collector\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate + on(namespace)group_left(pod)kube_pod_labels{label_app_kubernetes_io_component=\"collector\",label_app_kubernetes_io_managed_by=\"cluster-logging-operator\"}*0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Component Utilization",
   "type": "timeseries",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vector_utilization",
     "legendFormat": "{{pod}}/{{component_kind}}/{{component_type}}/{{component_id}}"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(node_namespace_pod_container:container_memory_rss + on(namespace)group_left(pod)kube_pod_labels{label_app_kubernetes_io_component=\"collector\",label_app_kubernetes_io_managed_by=\"cluster-logging-operator\"}*0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptor & Vector Open Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "vector_open_files{app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\"}",
     "legendFormat": "VOF:{{namespace}}/{{pod}}/{{container}}/{{component_kind}}/{{component_type}}"
    },
    {
     "expr": "container_file_descriptors{container=\"collector\"} + on(pod) group_left kube_pod_labels{label_app_kubernetes_io_component=\"collector\",label_app_kubernetes_io_part_of=\"cluster-logging\"}*0",
     "legendFormat": "FD: {{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer Size(events)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "vector_buffer_events{component_type!=\"prometheus_exporter\"}",
     "legendFormat": "{{pod}}/{{component_type}}/{{component_id}}"
    }
   ]
  },
  {
   "title": "Disk Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vector_buffer_byte_size{component_kind='sink', buffer_type='disk',app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\"}",
     "legendFormat": "{{pod}}/{{component_type}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Throughput Rate (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(pod,component_kind,component_id)(irate(vector_component_received_event_bytes_total{component_kind=\"source\", app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\",component_type!=\"internal_metrics\"}[5m]))",
     "legendFormat": "Collected {{pod}}/{{component_id}}"
    },
    {
     "expr": "sum by(pod,component_id)(irate(vector_component_sent_bytes_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\",app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\"}[5m]))",
     "legendFormat": "Sent {{pod}}/{{component_id}}"
    }
   ]
  },
  {
   "title": "Throughput Rate (events)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod,component_id)(irate(vector_component_received_events_total{component_kind=\"source\", app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\", component_type!=\"internal_metrics\"}[5m]))",
     "legendFormat": "Collected({{pod}}/{{component_id}})"
    },
    {
     "expr": "sum by (pod,component_id)(irate(vector_component_sent_events_total{component_kind=\"sink\", component_type!=\"prometheus_exporter\",app_kubernetes_io_component=\"collector\",app_kubernetes_io_part_of=\"cluster-logging\"}[5m]))",
     "legendFormat": "Sent({{pod}}/{{component_id}})"
    }
   ]
  },
  {
   "title": "HTTP Requests / Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (pod, component_id, error_kind)(vector_http_client_errors_total)",
     "legendFormat": "{{pod}}/{{component_id}} error: {{error_kind}}"
    },
    {
     "expr": "sum by (pod, component_id, error_kind)(vector_http_client_requests_sent_total)",
     "legendFormat": "{{pod}}/{{component_id}} requests"
    },
    {
     "expr": "sum by (pod, component_id, error_kind)(vector_http_client_responses_total)",
     "legendFormat": "{{pod}}/{{component_id}} responses"
    }
   ]
  },
  {
   "title": "Discard Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by (pod, component_id)(irate(vector_buffer_discarded_events_total{component_kind=\"sink\"}[2m]))",
     "legendFormat": "Buffer: {{pod}}/{{component_id}}"
    },
    {
     "expr": "sum by (pod, component_id)(irate(vector_component_discarded_events_total[2m]))",
     "legendFormat": "Component: {{pod}}/{{component_kind}}/{{component_id}}"
    }
   ]
  }
 ]
}