apiVersion: 1

providers:
- name: 'openshift-logging-dashboards'
  orgId: 1
  folder: 'OpenShift Logging'
  type: file
  disableDeletion: false
  updateIntervalSeconds: 10
  allowUiUpdates: false
  options:
    path: /var/lib/grafana/dashboards
    foldersFromFilesStructure: true
